version: '3.8'

services:
  aletheia-mail-agent:
    build: .
    container_name: aletheia-mail-agent
    environment:
      LOG_LEVEL: debug
      LOG_FORMAT: human_read

      EMAIL_SMTP_HOST: smtp.yandex.ru
      EMAIL_SMTP_PORT: 587
      EMAIL_USERNAME: data
      EMAIL_PASSWORD: data
      EMAIL_FROM: data




      KAFKA_BROKERS: kafka:29092
      KAFKA_CONSUMER_GROUP: mail-alert-agent-group

      TIMESCALE_USER: testuser
      TIMESCALE_PASSWORD: testpassword
      TIMESCALE_HOST: host.docker.internal
      TIMESCALE_DB: testdb_timescale
      TIMESCALE_PORT: 5433
    networks:
      - aletheia_network



networks:
  aletheia_network:
    external: true