version: '3.8'

services:
  aletheia-telegram-agent:
    build: .
    container_name: aletheia-telegram-agent
    environment:
      LOG_LEVEL: debug
      LOG_FORMAT: human_read

      TELEGRAM_BOT_TOKEN: token



      KAFKA_BROKERS: kafka:29092
      KAFKA_CONSUMER_GROUP: telegram-alert-agent-group

      TIMESCALE_USER: testuser
      TIMESCALE_PASSWORD: testpassword
      TIMESCALE_HOST: host.docker.internal
      TIMESCALE_DB: testdb_timescale
      TIMESCALE_PORT: 5433
    networks:
      - aletheia_network



networks:
  aletheia_network:
    external: true