// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/gofiber/fiber/v2"
)

func (http *httpApp) getMe(ctx context.Context, request requestAppGetMe) (response responseAppGetMe, err error) {

	response.Resp, err = http.svc.GetMe(ctx)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpApp) serveGetMe(ctx *fiber.Ctx) (err error) {

	var request requestAppGetMe

	var response responseAppGetMe
	if response, err = http.getMe(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
