// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import v1 "aletheia-public-api/interfaces/types/v1"

// Formal exchange type, please do not delete.
type requestAppGetMe struct{}

type responseAppGetMe struct {
	Resp v1.MeResponse `json:"resp,omitempty"`
}
