// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"aletheia-public-api/interfaces"
	v1 "aletheia-public-api/interfaces/types/v1"
	"context"
)

type AppGetMe func(ctx context.Context) (resp v1.MeResponse, err error)

type MiddlewareApp func(next interfaces.App) interfaces.App

type MiddlewareAppGetMe func(next AppGetMe) AppGetMe
