// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import v1 "aletheia-public-api/interfaces/types/v1"

type requestEventsGetEvents struct {
	PastHours int   `json:"pastHours,omitempty"`
	UserId    int64 `json:"userId,omitempty"`
}

type responseEventsGetEvents struct {
	Items v1.EventsResponse `json:"items,omitempty"`
}

type requestEventsGetEventByID struct {
	EventId string `json:"eventId,omitempty"`
	UserId  int64  `json:"userId,omitempty"`
}

type responseEventsGetEventByID struct {
	Resp v1.EventDetailResponse `json:"resp,omitempty"`
}

type requestEventsGetMostRecentEvent struct {
	UserId    int64  `json:"userId,omitempty"`
	EventType string `json:"eventType,omitempty"`
}

type responseEventsGetMostRecentEvent struct {
	Resp v1.EventDetailResponse `json:"resp,omitempty"`
}

type requestEventsGetEventsByType struct {
	EventType string `json:"eventType,omitempty"`
	UserId    int64  `json:"userId,omitempty"`
}

type responseEventsGetEventsByType struct {
	Resp v1.EventsByEventTypeResponse `json:"resp,omitempty"`
}
