// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import v1 "aletheia-public-api/interfaces/types/v1"

type requestProjectsGetProjects struct {
	UserId int64 `json:"userId,omitempty"`
}

type responseProjectsGetProjects struct {
	Items v1.ProjectsResponse `json:"items,omitempty"`
}

type requestProjectsGetProjectByID struct {
	ProjectID string `json:"projectID,omitempty"`
	UserId    int64  `json:"userId,omitempty"`
}

type responseProjectsGetProjectByID struct {
	Project v1.ProjectDetailResponse `json:"project,omitempty"`
}

type requestProjectsDeleteProjectByID struct {
	ProjectID string `json:"projectID,omitempty"`
	UserId    int64  `json:"userId,omitempty"`
}

type responseProjectsDeleteProjectByID struct {
	Status bool `json:"status,omitempty"`
}

type requestProjectsCreateProject struct {
	Project *v1.CreateProjectRequest `json:"project,omitempty"`
	UserId  int64                    `json:"userId,omitempty"`
}

type responseProjectsCreateProject struct {
	Status bool `json:"status,omitempty"`
}

type requestProjectsUpdateProject struct {
	Project   *v1.UpdateProjectRequest `json:"project,omitempty"`
	ProjectID string                   `json:"projectID,omitempty"`
	UserId    int64                    `json:"userId,omitempty"`
}

type responseProjectsUpdateProject struct {
	Status bool `json:"status,omitempty"`
}
