// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import v1 "aletheia-public-api/interfaces/types/v1"

type requestRulesGetRules struct {
	UserId int64 `json:"userId,omitempty"`
}

type responseRulesGetRules struct {
	Items v1.RulesResponse `json:"items,omitempty"`
}

type requestRulesGetRuleByID struct {
	UserId   int64  `json:"userId,omitempty"`
	RuleId   string `json:"ruleId,omitempty"`
	RuleType string `json:"ruleType,omitempty"`
}

type responseRulesGetRuleByID struct {
	Rule *v1.RuleDetailResponse `json:"rule,omitempty"`
}

type requestRulesGetAvailableRules struct {
	UserId int64 `json:"userId,omitempty"`
}

type responseRulesGetAvailableRules struct {
	Items v1.RulesResponse `json:"items,omitempty"`
}

type requestRulesDeleteRuleByID struct {
	UserId int64                `json:"userId,omitempty"`
	Req    v1.DeleteRuleRequest `json:"req,omitempty"`
}

type responseRulesDeleteRuleByID struct {
	Status bool `json:"status,omitempty"`
}

type requestRulesCreateRule struct {
	UserId  int64                `json:"userId,omitempty"`
	Request v1.CreateRuleRequest `json:"request,omitempty"`
}

type responseRulesCreateRule struct {
	Status bool `json:"status,omitempty"`
}

type requestRulesUpdateRuleById struct {
	UserId  int64                `json:"userId,omitempty"`
	Request v1.UpdateRuleRequest `json:"request,omitempty"`
}

type responseRulesUpdateRuleById struct {
	Status bool `json:"status,omitempty"`
}
